### ISSUE TITLE
Sparse Jacobian Assembly

### ISSUE THREAD

**Issue by JaredCrean2** [OptimalDesignLab/PDESolver.jl#12]
Currently the Jacobian is calculated and stored densely, which will get very slow and expensive for large problems.  We need to store it sparsely and only calculate the non zero entries.

The trick will be getting good performance.  When calculating the residual we calculate it all at once, performing the same operation over the entire mesh, which is very good for modern microprocessors.  Calculating the Jaocbian one block at a time would be easy, but slow.

Also, I suspect we will use a block sparse matrix when we move to Petsc, so we should make the code easily adaptable to that.

On the upside, because of node reordering, the jacobian should have a banded sparsity pattern.

**Comment by jehicken** [comment]
On the subject of block-sparse matrices... one can create a Block type that is used as the underlying type in SparseMatrix.  I experimented with this and verified that it can be done.  Whether or not this would help when moving to Petsc is not clear.

**Comment by JaredCrean2** [comment]
For sparse matrices, Julia calls external C libraries (UMFPACK for LU decomposition/solves), which I don't think support block matrices.  We will have to do block assembly for Petsc, but I don't think it will help for using Julia to do the linear solve.

**Comment by JaredCrean2** [comment]
This work as of f3ff380.  Closing
