### ISSUE TITLE
reducing coupling between nonlinear solver and residual/jacobian calculation

### ISSUE THREAD

**Issue by j4yan** [OptimalDesignLab/PDESolver.jl#123]
Currently, a couple of functions and parameters are passed into the nonlinear solver 'newton':
```
newton(evalEuler, mesh, sbp, eqn, opts, pmesh, itermax=opts["itermax"], 
                 step_tol=opts["step_tol"], res_abstol=opts["res_abstol"], 
                 res_reltol=opts["res_reltol"], res_reltol0=opts["res_reltol0"])
```

inside which the jacobian matrix is calculated using colored finite difference. We can see that function `newton` depends on all kinds of parameters. I suggest that the nonlinear function should only take whatever is necessary, including
`calcResidual(q, res)`, `alcJacobian(q, Jac)`, `newtonParameters`, 
```calcResidual(q)``` and ```calcJacobian(q, Jac)``` are actually anonymous functions (functor/lambda function in C++). 

In this way there would be much less coupling between the nonlinear solver and residual calculation, and we can pass in difference functions to compute the Jacobian matrix. We can also do the same thing to `linearSolver`, `preconditioner`.

Here is an example showing it's doable:

```
function newtonInterate(func::Function, dfdx::Function, x0::Float64=0.0)
    max_iter = 50
    tol = 1.e-8
    x = x0
    for i = 1 : max_iter
        dx = func(x) / dfdx(x)
        x = x - dx;
        if abs(dx) < tol return x end
    end
    return x 
end
function foo(x, a)
    return (x - a) * (x - a)
end

function dfoodx(x, a)
    return 2*(x - a) 
end

function solve(a)
    f(x) = foo(x, a)
    dfdx(x)= dfoodx(x, a)
    x = newtonInterate(f, dfdx)
    println("x = $x")
end
```

**Comment by jehicken** [comment]
Would the preconditioner also need to be provided here?  I would think so, but I have not looked at how Ticon implements Newton in detail recently.

**Comment by j4yan** [comment]
I guess yes. But we can define the default preconditioner and anonymous functions for all physics (AbstractSolutionData?). If the users want something special, then can just define their own versions.

**Comment by jehicken** [comment]
I think it is hard to separate Newton from the method used to solve the linear system.  We almost need two Newtons, one for direct solves and one for iterative solves.

**Comment by JaredCrean2** [comment]
I think this has been largely accomplished with the new `AbstractPC`, `AbstractLO` and `LinearSolver` interface.  The signature for `newton_inner` now looks like [this](https://github.com/OptimalDesignLab/PDESolver.jl/blob/work/src/NonlinearSolvers/newton.jl#L131).  The `LinearSolver` contains a linear operator and a preconditioner, each of which have methods for computing and applying the operators (see docs [here](http://www.optimaldesignlab.com/PDESolver.jl/linearsolvers/linearsolvers.html)).  If we need more separation than this, we can certainly continue discussion.

**Comment by JaredCrean2** [comment]
Closing this.  Someone can reopen if they wan to continue discussing.
