### ISSUE TITLE
NaN found when obtaining start coords for reordering

### ISSUE THREAD

**Issue by ashleaRPI** [OptimalDesignLab/PDESolver.jl#160]
We use a starting point at which we look for the nearest entity. The y-coordinate is NaN (specifically `-nan`). 

Example output:
```
number of triangle 3998 quad 0
mesh entity counts: v 2051 e 6049 f 3998 r 0
mesh reordered in 0.005800 seconds
writeVtuFile into buffers: 0.024564 seconds
writeVtuFile buffers to disk: 0.011867 seconds
vtk files output_init written in 0.042856 seconds
requested starting coordinates = 0, -nan
starting entity coordinates = (9.99841, 0.178177, 0)
```

**Comment by JaredCrean2** [comment]
This doesn't happen during the tests.  Can you provide a reproducible test case?

**Comment by JaredCrean2** [comment]
Stumbled upon the likely cause of this.  Will be fixed in PumiInterface when my current branch gets merged.
