### ISSUE TITLE
Duplication of work within NonLinearSolvers module

### ISSUE THREAD

**Issue by k1nshuk** [OptimalDesignLab/PDESolver.jl#18]
It would be nice to have all the internal functions like the ones used for calculating the jacobian of the residual to be globally available.

**Comment by JaredCrean2** [comment]
Why?  When are they needed outside the `NonlinearSolvers` module?

**Comment by k1nshuk** [comment]
RK4 within `NonlinearSolvers` module does not make the function call `calcResidual`. Instead actions assembly/disassembly of solution and function evaluation are carried out carried out explicitly. (for instance, Lines 235-239)

**Comment by JaredCrean2** [comment]
`rk4.jl` is part of `NonlinearSolvers`, so there is no need to export `calcResidual`.  `rk4.jl` does need to be cleaned up and having something like `calcResidual` would certainly help.

Because this is part of code cleanup, I'm closing this in favor of #43
