### ISSUE TITLE
Recalculating Euler Flux in Roe Solver

### ISSUE THREAD

**Issue by JaredCrean2** [OptimalDesignLab/PDESolver.jl#2]
The Roe solver in solver/euler/bc_solvers.jl recalculates the Euler flux from scratch rather than taking a combination of the precomputed fluxes in eqn.F_xi.  This is bad for performance

**Comment by jehicken** [comment]
There are two ways I think we can solve this.  The first, which I think you are suggesting, is to pass in F_xi and use it.  The second, is to rewrite the Roe solver slightly.  The second option can be done with almost negligible expense.
