### ISSUE TITLE
Vector Assembly and Disassembly Function

### ISSUE THREAD

**Issue by JaredCrean2** [OptimalDesignLab/PDESolver.jl#25]
Currently the function that copy data back and forth between the 3-d (element) arrays and their corresponding vector form live inside the different physics modules.  I think this is mostly a historical artifact.  Should those live somewhere else (perhaps in ODLCommonTools?)?  I can't think of any reason why these functions are physics-specific.

**Comment by jehicken** [comment]
I think it is ok being a utils of PDESolver.

**Comment by JaredCrean2** [comment]
I can't find the commit that closed this, but these functions now live in `src/Utils`.  Closing.
