### ISSUE TITLE
Functions for calculating residuals in Non-Linear Solvers

### ISSUE THREAD

**Issue by k1nshuk** [OptimalDesignLab/PDESolver.jl#28]
RK4 method needs a function similar to calcResidual in newton_fd.jl. Its a cleaner way of doing things than assembling and disassembling solutions and residuals within the non-linear solvers. In addition, I think it will be better to have the function to evaluate the residual under the PDE module we are solving for (Advection/Euler) allowing the nl-solver to be agnostic of the equation we are solving.

**Comment by JaredCrean2** [comment]
I can't find the commit that did this, but the rewrite of rk4 a while ago encapsulated the assembling and disassembling of things, so rk4 is much more general now (in fact, it is possible to it use as a time marcher for a stateless ODE rather than a PDE).
