### ISSUE TITLE
arg_dict_output.txt printing wrong output

### ISSUE THREAD

**Issue by k1nshuk** [OptimalDesignLab/PDESolver.jl#34]
arg_dict_output.txt is printing incorrect values. the dictionary specifies use_SUPG as true, but arg_dict_output.txt doesnt recognize it

**Comment by JaredCrean2** [comment]
Can you provide an input_vals.jl file that reproduces this?

**Comment by JaredCrean2** [comment]
Unless there is a reproducible example, I am more inclined to believe this is a problem with your input file than the code.  The code for creating `arg_dict_output.txt` is really simple, so there is not much opportunity for a bug.

**Comment by JaredCrean2** [comment]
Closing this, please reopen if a reproducible example becomes available
