### ISSUE TITLE
Fewer output files

### ISSUE THREAD

**Issue by ashleaRPI** [OptimalDesignLab/PDESolver.jl#36]
Only what's necessary

**Comment by JaredCrean2** [comment]
Is there a more specific definition for this?  "necessary" can have many meanings.  What is necessary when debugging is different from what is necessary when running to get results, and there are lots of states in-between.

**Comment by JaredCrean2** [comment]
At this point only a few files get printed by default.  Closing this for now, please reopen if there is a specific idea for which files to print.
