### ISSUE TITLE
How Many Type Paramters?

### ISSUE THREAD

**Issue by JaredCrean2** [OptimalDesignLab/PDESolver.jl#4]
We seem to be accumulating type parameters rather quickly.  In order to (efficiently) differentiate the code with respect to both the state variables and coordinates, we need at least two parameters, and SBP has one, so that brings us to three independent parameters.  Different quantities are computed using quantities of the different types, leading to the possiblity of 7 type parameters total (3 independent, 3 non-repeating combinations of two, and one combination of all 3 independent parameters).  This seems like a lot.

Is there any way we can simplify this.  Perhaps we can assume the SBP type is always a 'lesser' type than the other, ie. `promote(Tmsh, Tsbp) = Tmsh; promote(Tsol, Tsbp) = Tsol)`?  
@jehicken

**Comment by jehicken** [comment]
I am not sure if PDESolver will ever need to parameterize the SBP operator.  Can you describe a use case?  You might be able to assume Tsbp = Float64.

**Comment by JaredCrean2** [comment]
The only case I can think of is if SBP is using higher precision, then some of the solution data arrays will have to as well to avoid an `InexactError` when a `BigFloat` is written to an array of `Float64`.  

I suppose this case could be handled by making the type used to construct the SBP operator dependent on one (or more) of the others, ensuring the 'lesser' type condition is satisfied.

If there are no objections, I'll go ahead and remove any parameterization on Tsbp.

**Comment by jehicken** [comment]
No objections, as long as by "remove" you are referring to PDESolver.jl only, and not SummationByParts.jl.

**Comment by JaredCrean2** [comment]
Yes, indeed.  If I wanted a change to SBP I would create an issue on the SBP github.
