### ISSUE TITLE
Resolve SCOREC unicode issue

### ISSUE THREAD

**Issue by ashleaRPI** [OptimalDesignLab/PDESolver.jl#41]
unicode characters aren't reliably showing up when ssh'd into SCOREC machines (using vi)

**Comment by JaredCrean2** [comment]
@ashleaRPI I believe you did this, so you get the honor of closing the issue.

**Comment by ashleaRPI** [comment]
Here's my vimrc settings that fixed it.

 if has("multi_byte")
   set encoding=utf-8
   set fileencoding=utf-8
   set fileencodings=ucs-bom,utf-8,latin1
   set termencoding=utf-8
 endif
