### ISSUE TITLE
Tighter Sparsity Bounds

### ISSUE THREAD

**Issue by JaredCrean2** [OptimalDesignLab/PDESolver.jl#49]
It should be possible to get tighter sparsity bounds for the Jacobian.  Currently the code looks at the maximum and minimum dof that each dof interacts with, and allocates a the space `Jac[min_dof:max_dof, current_dof]` to be non-zero.  It turns out there are substantial regions within `min_dof:max_dof` that will always be zero based on the structure of the mesh.  It would be better to only allocate the non-zeros that will actually be used, rather than large ranges of non-zeros, only some of which will be used.

Todos:
- [ ] get the exact sparsity pattern in PumiInterface
- [ ] create a function to preallocate the jacobian based on the exact sparsity pattern (in `ODLCommonTools/sparse.jl`)
- [ ] rewrite`get/setindex!` functions in `ODLComonTools/sparse.jl` to not assume the non-zero region of the each Jacobian column is continuous

**Comment by JaredCrean2** [comment]
The sorted array search needed for the last Todo is now in ODLCommontools, called `fastfind()`

**Comment by jehicken** [comment]
Is this for the general case (i.e. CG)?  Because, the sparsity of DG is known a priori.

**Comment by JaredCrean2** [comment]
Yes, for all cases.  The jacobian is constructed after the mesh is initialized, and once the mesh is initialized the sparsity pattern can be computed with a single walk of the graph.  So in all cases the sparsity pattern is known.

**Comment by JaredCrean2** [comment]
This is now done for DG meshes [here](https://github.com/OptimalDesignLab/ODLCommonTools.jl/blob/master/src/sparse.jl#L17).  CG still needs to be done.

**Comment by JaredCrean2** [comment]
CG is no longer under active development, so I'm closing this.  We can reopen if CG becomes relevant in the future.
