### ISSUE TITLE
Use Input Dictionary for Everything

### ISSUE THREAD

**Issue by JaredCrean2** [OptimalDesignLab/PDESolver.jl#5]
A new input parser/dictionary thing was added ff39749 (see file input.jl).  I think we should use this for getting/setting *all* runtime options, for consistency and clarity.  The `opts` dictionary should be passed around with `eqn` and `mesh` to all high and mid level functions so they can access any needed options.  This could also be helpful for #3 .

**Comment by jehicken** [comment]
Acting as "devil's advocate"... the eqn and mesh types are high level objects, and I think there is merit to leaving them out of the `optns` dictionary.  In the extreme case, we could put all of a function's inputs into a dictionary, but readability would be lost.

**Comment by jehicken** [comment]
Upon further reflection, I think `opts` should contain only scalar parameters.

Or, by "passed around with..." did you mean as a group, rather than with `eqn` and `mesh` embedded?

**Comment by JaredCrean2** [comment]
Yes, I think the arguments for all the high and mid level functions should be `mesh, sbp, eqn, opts`.

**Comment by jehicken** [comment]
Sounds good.  This model has the following associations:

* `mesh` = ...mesh
* `sbp` = element-level discretization
* `eqn` = PDE being solved *and the solution*
* `opts` = options

This makes me wonder if `eqn` should not be further decomposed into `eqn` and `sol`, where the latter stores all of the data in arrays.  Thoughts?

**Comment by JaredCrean2** [comment]
Currently `eqn` is almost entirely arrays with a few constants (cv, gamma, etc).  It might make sense to have a `constants` object as a member of `eqn`.  Typically all the arrays (`q`, `F_xi`, `res` etc) are all needed together, so I think keeping them in one object makes sense.

**Comment by jehicken** [comment]
Ok, then I guess my objection is with the name.  `eqn` suggests equation, but the type really holds solution data related to an equation.  I leave the decision to you, but what about
`AbstractEquation` becomes `SolutionData`
`EulerEquation`  becomes `EulerData <: SolutionData`

**Comment by jehicken** [comment]
Returning to the issue at hand...

Here is a short list of parameters that you should include in `opts`.  I think it makes sense to have a dictionary of dictionaries, to organize the options.  This will also make it easier to pass sub-options down to lower level methods.  Consider defining the `opts` in its own module where you can set the default values.

**options related to the flow/operating conditions**
* angle of attack (aoa) in degrees (convert to radius for actual use in code)
* free-stream Mach number
* free-stream Reynolds number (nondimensionalized based on the root chord)

**options related to the discretization**
* degree of the SBP operator
* parameters associated with the stabilization
* parameters associated with the shock capturing scheme

**options related to the primal (state) solver**
* relative residual tolerance
* linear tolerance schedule (i.e. how the inexact Newton tolerance is updated)
* type of Krylov iterative method and its options (separate dictionary?)
* type of preconditioner and its options (separate dictionary?)

**Comment by JaredCrean2** [comment]
These all look like useful parameters.  While normally I support more structure in the code, I think having a dictionary of dictionaries increases complexity (because different parts of the code will need different sub-dictionaries) without increasing organization (because functions can ignore irrelevant keys).  I'm content to use one dictionary for  now, and breaking it up into sub-dictionaries later if it becomes unmanageable, if that works for you.

**Comment by JaredCrean2** [comment]
Regarding the name of the `Equation` objects, yeah, those are no longer accurate.  I'll change those at some point.

**Comment by jehicken** [comment]
One dictionary is fine for now.
