### ISSUE TITLE
Make Petsc Jacobian Assembly Faster

### ISSUE THREAD

**Issue by JaredCrean2** [OptimalDesignLab/PDESolver.jl#50]
I turns out that inserting values into a Petsc matrix is rather slow:

```
t_insert : (time spent calling MatSetValues() )
  35.49
t_jacobian:  (total time spent constructing the Jacobian
  153.33
t_func: (time spent evaluating the residual while constructing the Jacobian)
  115.46
```

However, I did a little experiment where I tripled the amount of data passed to `MatSetValues` per call (and kept the total number of calls constant, so there is net 3x more data being put into the Jacobian) and `t_insert` increased to 78.30 (roughly 2x increase).  So it looks like there is significant overhead in calling `MatSetValues`.

Possible solution: Reorganize `calcJacobianSparse` [here](https://github.com/OptimalDesignLab/PDESolver.jl/blob/master/src/NonlinearSolvers/newton.jl#L946).  Currently it loops over all elements in the residual, figures out which dof on which element perturbed the current element, and inserts the values for the current element into the Jacobian.  For any case where a distance-k coloring is used for k >= 1, a single element perturbs itself and all of its neighbors at the same time, so values for all of those element can be inserted in a single call to `MatSetValues`.  The net result is there is 1 call to `MatSetValues` per perturbed element, rather than 1 call per element in the mesh.

**Comment by JaredCrean2** [comment]
It is also true that this problem will be less pronounced for higher order and 3D meshes, because they have more nodes per element.  It will also be better for vector PDEs because they have more dofs per node.

**Comment by jehicken** [comment]
Another option: Petsc accepts a matrix vector operator.  We could perform the products on our side using complex-step, for example.  However, this does not resolve preconditioning, nor does it help with transposed products.

**Comment by JaredCrean2** [comment]
That is true, this problem does not affect matrix-vector products (which we do support [here](https://github.com/OptimalDesignLab/PDESolver.jl/blob/master/src/NonlinearSolvers/newton.jl#L761) )

**Comment by JaredCrean2** [comment]
This is handled correctly by the explicit Jacobian calculation work (which makes the Jacobian 5x to 10x faster to compute), so getting an extra 30 or 40% in the coloring case doesn't seem worth it.
