### ISSUE TITLE
ICs & BCs outside of source code

### ISSUE THREAD

**Issue by ashleaRPI** [OptimalDesignLab/PDESolver.jl#62]
A user who wants to run a new case needs to have repo write access. 

A possible better way of running Ticon is:
- User specifies a input_vals.jl, which has keys that point to a file that defines an IC and a file that defines a BC
- User writes the IC file
- User writes the BC file

**Comment by JaredCrean2** [comment]
Did this as part of the front end rewrite over winter break.
