### ISSUE TITLE
interpolation issue in output (not smooth as it should be)

### ISSUE THREAD

**Issue by j4yan** [OptimalDesignLab/PDESolver.jl#66]
When the solutions are output and plotted in Paraview, we can see that solutions around interior faces are not smooth at all.

![interp_issue_1](https://cloud.githubusercontent.com/assets/19536639/19051539/5dbee790-8981-11e6-8828-2c097f5803d2.png)
![interp_issue](https://cloud.githubusercontent.com/assets/19536639/19051540/5dbf3cfe-8981-11e6-82ee-09df87588d32.png)

**Comment by JaredCrean2** [comment]
@j4yan Check out the `build_system` branch of PumiInterface and see if that fixes the problem

**Comment by JaredCrean2** [comment]
Closing this old issue.  Please reopen if there is still a problem
