### ISSUE TITLE
newton.jl test: jac_type == 1 not tested

### ISSUE THREAD

**Issue by ashleaRPI** [OptimalDesignLab/PDESolver.jl#69]
Looks like the jac_type == 1 case in setupNewton wasn't tested. Ran into an issue where m wasn't defined, which only arose when I ran a test case instead of running tests.

**Comment by JaredCrean2** [comment]
Tangentially related: there is a file `test/advection/test_newton.jl` that is currently not run because it was set up to use CG rather than DG (CG is currently broken).  I think fixing the tests there and adding a test for `jac_type == 1` is the right way to fix this.

**Comment by JaredCrean2** [comment]
It looks like the file `euler/test_modes.jl` contains a test for `jac_type = 1`, but the file is not currently run because it uses CG, which doesn't work quite right.  Restoring these tests it probably the best fix.

**Comment by JaredCrean2** [comment]
`test_modes.jl` has been updated to use DG rather than CG, and is running again as part of the CI tests.
